package com.github.nrudenko.orm.example.schemas;

import com.github.nrudenko.orm.commons.BaseScheme;
import com.github.nrudenko.orm.commons.Column;
import com.github.nrudenko.orm.commons.DbType;
import com.github.nrudenko.orm.example.model.Attach;
import com.github.nrudenko.orm.example.model.ExampleModel;


/* AUTO-GENERATED FILE. CAREFUL TO MODIFY.
 *
 * This class was automatically generated by the
 * OrmGeneratorPlugin any changes will be overwritten
 * after next schema auto-generation
 */

public final class ExampleModelScheme implements BaseScheme {

    public static final Column _ID = new Column("ExampleModel._id", DbType.INT); // PRIMARY AUTOINCREMENT
    public static final Column TEXT = new Column("ExampleModel.text", DbType.TEXT);
    public static final Column DATE = new Column("ExampleModel.date", DbType.NUMERIC);
    public static final Column INT_VAL = new Column("ExampleModel.intVal", DbType.INT);

    public static Class MODEL_CLASS = ExampleModel.class;
    public static Column[] PROJECTION = new Column[]{_ID, TEXT, DATE, INT_VAL};
    public static String CUSTOM_SQL= "";
    public static String TABLE_NAME = "example_model";
}